### ISSUE TITLE
Иконки в редакторе изображений

### ISSUE THREAD

**Issue by Ankhena** [Barsik1976/656475-pink-22#10]
Контентные или украшения?

![2021-04-02_18-45-43](https://user-images.githubusercontent.com/20879307/113430936-afba1800-93e3-11eb-84b2-c1d4e0eeb0bd.jpg)

**Comment by Barsik1976** [comment]
Украшения?  А нельзя оставить контентными?

**Comment by Ankhena** [comment]
Они же не являются контентными?
Вообще, это будет SVG спрайт.
