### ISSUE TITLE
Alt с большой буквы

### ISSUE THREAD

**Issue by Ankhena** [Barsik1976/656475-pink-22#11]
Все тексты в разметке пишутся по правилам языка страницы. 
Сейчас они не видны, но они могут быть показаны в сниппете поисковой выдачи или их могут спарсить какие угодно роботы и показывать.

Это касается всего проекта, всех alt, title, vusually-hidden

**Comment by Barsik1976** [comment]
В первый раз слышу и вижу так.  Это alt, которые описывают img?

**Comment by Ankhena** [comment]
Если что, то я про содержимое атрибута.
